-- Notifications Table
create table notifications (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) on delete cascade not null,
  type text not null, -- 'message', 'comment', 'badge', 'system'
  title text not null,
  content text,
  link text, -- optional redirect path
  is_read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies
alter table notifications enable row level security;

create policy "Users can view their own notifications"
  on notifications for select
  using (auth.uid() = user_id);

create policy "Users can update their own notifications"
  on notifications for update
  using (auth.uid() = user_id);

-- Enable realtime for notifications
alter publication supabase_realtime add table notifications;

-- Function to create notification for new direct message
create or replace function notify_on_new_message()
returns trigger as $$
declare
  recipient_id uuid;
  sender_name text;
begin
  -- Find the recipient (the user in the conversation who is NOT the sender)
  select case 
    when user1_id = new.sender_id then user2_id
    else user1_id 
  end into recipient_id
  from conversations
  where id = new.conversation_id;

  -- Get sender's username
  select username into sender_name from profiles where id = new.sender_id;

  insert into notifications (user_id, type, title, content, link)
  values (
    recipient_id,
    'message',
    'New Message from ' || sender_name,
    new.content,
    '/messages'
  );

  return new;
end;
$$ language plpgsql security definer;

-- Trigger for new message notification
create trigger on_new_message_notification
after insert on direct_messages
for each row execute procedure notify_on_new_message();

-- Function to create notification for new comment
create or replace function notify_on_new_comment()
returns trigger as $$
declare
  thread_author_id uuid;
  comment_author_name text;
  thread_title text;
begin
  -- Find thread author and title
  select author_id, title into thread_author_id, thread_title from threads where id = new.thread_id;
  
  -- Don't notify if the author of the thread is the one commenting
  if thread_author_id = new.author_id then
    return new;
  end if;

  -- Get comment author's username
  select username into comment_author_name from profiles where id = new.author_id;

  insert into notifications (user_id, type, title, content, link)
  values (
    thread_author_id,
    'comment',
    'New Comment on your post',
    comment_author_name || ' commented on: ' || thread_title,
    '/forums/' || new.thread_id
  );

  return new;
end;
$$ language plpgsql security definer;

-- Trigger for new comment notification
create trigger on_new_comment_notification
after insert on comments
for each row execute procedure notify_on_new_comment();
