-- 1. Direct Messaging System

-- Conversations Table (Tracks the relationship between two users)
create table conversations (
  id bigint generated by default as identity primary key,
  user1_id uuid references profiles(id) not null,
  user2_id uuid references profiles(id) not null,
  last_message_at timestamp with time zone default timezone('utc'::text, now()) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user1_id, user2_id) -- Ensure one conversation per pair
);

-- Constraint to ensure user1_id < user2_id to prevent duplicates like (A, B) and (B, A)
-- Note: In application logic, always sort IDs before inserting/querying: 
-- [min(id1, id2), max(id1, id2)]

-- Direct Messages Table
create table direct_messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint references conversations(id) on delete cascade not null,
  sender_id uuid references profiles(id) not null,
  content text not null,
  is_read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Dynamic Student Tags (Badges)

-- Add badges column to profiles
alter table profiles 
add column if not exists badges text[] default array[]::text[];

-- Function to check and award badges based on high performance
create or replace function check_performance_badges()
returns trigger as $$
declare
  subject_name text;
  avg_score numeric;
  test_count int;
  existing_badges text[];
  new_badge text;
begin
  -- Get the category name of the test
  select name into subject_name from categories
  where id = (select category_id from tests where id = new.test_id);

  if subject_name is null then
    return new;
  end if;

  -- "Master" Title Logic:
  -- User must have taken at least 3 tests in this category
  -- Average percentage must be >= 90%
  
  select avg(percentage), count(*) into avg_score, test_count
  from results r
  join tests t on r.test_id = t.id
  join categories c on t.category_id = c.id
  where r.user_id = new.user_id 
  and c.name = subject_name;

  if test_count >= 3 and avg_score >= 90 then
    -- Determine badge name
    if subject_name = 'Mathematics' then new_badge := 'Master Mathematician';
    elsif subject_name = 'Physics' then new_badge := 'Super Physicist';
    elsif subject_name = 'Chemistry' then new_badge := 'Alchemist';
    else new_badge := 'Master ' || subject_name;
    end if;

    -- Update profile badges if they don't have it yet
    select badges into existing_badges from profiles where id = new.user_id;
    
    if not (existing_badges @> array[new_badge]) then
      update profiles 
      set badges = array_append(badges, new_badge)
      where id = new.user_id;
    end if;
  end if;

  return new;
end;
$$ language plpgsql security definer;

-- Trigger the function after every new test result
drop trigger if exists on_new_result_badge_check on results;
create trigger on_new_result_badge_check
after insert on results
for each row execute procedure check_performance_badges();
