-- Create profiles table (extends auth.users)
create table profiles (
  id uuid references auth.users not null primary key,
  username text unique,
  avatar_url text,
  level int default 1,
  xp int default 0,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Categories for Threads and Tests
create table categories (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text unique not null,
  icon text,
  color text
);

-- Forum Threads
create table threads (
  id bigint generated by default as identity primary key,
  title text not null,
  body text not null,
  category_id bigint references categories(id),
  author_id uuid references profiles(id) not null,
  views int default 0,
  tags text[],
  is_pinned boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Forum Comments
create table comments (
  id bigint generated by default as identity primary key,
  body text not null,
  thread_id bigint references threads(id) on delete cascade not null,
  author_id uuid references profiles(id) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Mock Tests
create table tests (
  id bigint generated by default as identity primary key,
  title text not null,
  description text,
  category_id bigint references categories(id),
  duration_minutes int not null,
  difficulty text check (difficulty in ('Easy', 'Medium', 'Hard')),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Test Questions
create table questions (
  id bigint generated by default as identity primary key,
  test_id bigint references tests(id) on delete cascade not null,
  content text not null,
  options jsonb not null, -- Array of strings e.g. ["Opt A", "Opt B", "Opt C", "Opt D"]
  correct_option int not null, -- Index of correct option (0-3)
  marks int default 4
);

-- User Test Results
create table results (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) not null,
  test_id bigint references tests(id) not null,
  score int not null,
  total_marks int not null,
  percentage numeric,
  time_taken_seconds int,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Insert dummy categories
insert into categories (name, slug, icon, color) values
('Physics', 'physics', 'Atom', 'blue'),
('Chemistry', 'chemistry', 'Flask', 'purple'),
('Mathematics', 'mathematics', 'Calculator', 'red'),
('General', 'general', 'MessageCircle', 'gray');
