-- Groups Table
create table groups (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  created_by uuid references profiles(id) not null,
  is_private boolean default true,
  invite_code text unique, -- 6 character code
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Group Members Table
create table group_members (
  id bigint generated by default as identity primary key,
  group_id bigint references groups(id) on delete cascade not null,
  user_id uuid references profiles(id) not null,
  role text default 'member' check (role in ('admin', 'member')),
  joined_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(group_id, user_id)
);

-- Group Messages Table
create table group_messages (
  id bigint generated by default as identity primary key,
  group_id bigint references groups(id) on delete cascade not null,
  author_id uuid references profiles(id) not null,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
