-- Create shop_items table
create table if not exists shop_items (
  id bigint generated by default as identity primary key,
  name text not null,
  description text,
  cost int not null default 0,
  type text check (type in ('frame', 'title', 'utility')) not null,
  value text not null, -- CSS class for frames, text for titles, function ref for utility
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create user_inventory table
create table if not exists user_inventory (
  id bigint generated by default as identity primary key,
  user_id uuid references profiles(id) not null,
  item_id bigint references shop_items(id) not null,
  is_equipped boolean default false,
  obtained_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS
alter table shop_items enable row level security;
alter table user_inventory enable row level security;

create policy "Shop items viewable by everyone" on shop_items for select using (true);

create policy "Inventory viewable by owner" on user_inventory for select using (auth.uid() = user_id);
create policy "Inventory insertable by owner" on user_inventory for insert with check (auth.uid() = user_id);
create policy "Inventory updateable by owner" on user_inventory for update using (auth.uid() = user_id);

-- Seed Items
insert into shop_items (name, description, cost, type, value) values
('Neon Warrior', 'A glowing green border for true fighters.', 500, 'frame', 'border-neon-green'),
('Cyber Punk', 'Blue and pink glitch effect.', 1000, 'frame', 'border-neon-pink'),
('Golden God', 'Pure gold radiance for the top 1%.', 5000, 'frame', 'border-gold-500'),
('The Scholar', 'Title for the learned.', 200, 'title', 'The Scholar'),
('Focus Master', 'Title for those who never blink.', 500, 'title', 'Focus Master'),
('Streak Freeze', 'Protect your streak for one day.', 100, 'utility', 'freeze_streak');
